title: JVCSSoftware
email: jvcs.mecatronica@gmail.com
domain: jvcss.github.io
description: >-
  Made with ❤️ 
baseurl: ''
url: "https://jvcss.github.io"
twitter_username: jvictorcard
youtube_username: @jvcss
github_username:  jvcss

theme: minima
plugins:
  - jekyll-feed
